/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as ExperimentRouteImport } from './routes/experiment'
import { Route as FederatedLearningRouteImport } from './routes/federated-learning'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as OtraceRouteImport } from './routes/otrace'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SourceCodeRouteImport } from './routes/source-code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentRoute = ExperimentRouteImport.update({
  id: '/experiment',
  path: '/experiment',
  getParentRoute: () => rootRouteImport,
} as any)
const FederatedLearningRoute = FederatedLearningRouteImport.update({
  id: '/federated-learning',
  path: '/federated-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const OtraceRoute = OtraceRouteImport.update({
  id: '/otrace',
  path: '/otrace',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceCodeRoute = SourceCodeRouteImport.update({
  id: '/source-code',
  path: '/source-code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evaluation': typeof EvaluationRoute
  '/experiment': typeof ExperimentRoute
  '/federated-learning': typeof FederatedLearningRoute
  '/gdpr': typeof GdprRoute
  '/otrace': typeof OtraceRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/source-code': typeof SourceCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evaluation': typeof EvaluationRoute
  '/experiment': typeof ExperimentRoute
  '/federated-learning': typeof FederatedLearningRoute
  '/gdpr': typeof GdprRoute
  '/otrace': typeof OtraceRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/source-code': typeof SourceCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evaluation': typeof EvaluationRoute
  '/experiment': typeof ExperimentRoute
  '/federated-learning': typeof FederatedLearningRoute
  '/gdpr': typeof GdprRoute
  '/otrace': typeof OtraceRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/source-code': typeof SourceCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/evaluation'
    | '/experiment'
    | '/federated-learning'
    | '/gdpr'
    | '/otrace'
    | '/reports'
    | '/settings'
    | '/source-code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/evaluation'
    | '/experiment'
    | '/federated-learning'
    | '/gdpr'
    | '/otrace'
    | '/reports'
    | '/settings'
    | '/source-code'
  id:
    | '__root__'
    | '/'
    | '/evaluation'
    | '/experiment'
    | '/federated-learning'
    | '/gdpr'
    | '/otrace'
    | '/reports'
    | '/settings'
    | '/source-code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvaluationRoute: typeof EvaluationRoute
  ExperimentRoute: typeof ExperimentRoute
  FederatedLearningRoute: typeof FederatedLearningRoute
  GdprRoute: typeof GdprRoute
  OtraceRoute: typeof OtraceRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SourceCodeRoute: typeof SourceCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiment': {
      id: '/experiment'
      path: '/experiment'
      fullPath: '/experiment'
      preLoaderRoute: typeof ExperimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/federated-learning': {
      id: '/federated-learning'
      path: '/federated-learning'
      fullPath: '/federated-learning'
      preLoaderRoute: typeof FederatedLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otrace': {
      id: '/otrace'
      path: '/otrace'
      fullPath: '/otrace'
      preLoaderRoute: typeof OtraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source-code': {
      id: '/source-code'
      path: '/source-code'
      fullPath: '/source-code'
      preLoaderRoute: typeof SourceCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvaluationRoute: EvaluationRoute,
  ExperimentRoute: ExperimentRoute,
  FederatedLearningRoute: FederatedLearningRoute,
  GdprRoute: GdprRoute,
  OtraceRoute: OtraceRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SourceCodeRoute: SourceCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}